#-------------------------------------------------------------------------------
# Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
# Distributed under the Boost Software License, Version 1.0.
# 
# Boost Software License - Version 1.0 - August 17th, 2003
# 
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
# 
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#-------------------------------------------------------------------------------

# Default target
.DEFAULT_GOAL := all

#-------------------------------------------------------------------------------
# Build type
#-------------------------------------------------------------------------------

# Checks if we're on OS-X to determine the build type
ifeq ($(findstring Darwin, $(shell uname)),)
    BUILD_TYPE  := linux
else
    BUILD_TYPE  := os-x
endif

# Host architecture
HOST_ARCH := $(shell uname -m)

#-------------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------------

MAKE    := make -s
SHELL   := /bin/bash
_CC      = $(CC) $(FLAGS_WARN) -fPIC -$(FLAGS_OPTIM) -std=$(FLAGS_STD) $(FLAGS_OTHER) -I$(DIR_INC)

# C compiler - Debug mode
ifneq ($(findstring 1,$(DEBUG)),)
_CC     += -DDEBUG=1
_CC     += -g
endif

#-------------------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------------------

# Make version (version 4 allows parallel builds with output sync) 
MAKE_VERSION_MAJOR  := $(shell echo $(MAKE_VERSION) | cut -f1 -d.)
MAKE_4              := $(shell [ $(MAKE_VERSION_MAJOR) -ge 4 ] && echo true)

# Check for the xctool utility
XCTOOL              := $(shell which xctool)
HAS_XCTOOL          := $(shell if [ -f "$(XCTOOL)" ]; then echo true; else echo false; fi )

# Check for the xcodebuild utility
XCBUILD             := $(shell which xcodebuild)
HAS_XCBUILD         := $(shell if [ -f "$(XCBUILD)" ]; then echo true; else echo false; fi )

ifeq ($(HAS_XCBUILD),true)
MAC_TARGET          := $(shell $(XCBUILD) -showsdks | grep macosx | tail -1 | perl -pe 's/[^-]+-sdk [^0-9]+(.*)/\1/g')
IOS_SDK             := $(shell $(XCBUILD) -showsdks | grep iphoneos | tail -1 | perl -pe 's/[^-]+-sdk [^0-9]+(.*)/\1/g')
IOS_SDK_PATH        := /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$(IOS_SDK).sdk
XCODE_SDK_VALUE     := "$(shell /usr/libexec/PlistBuddy -c "Print $(1)" /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist)"
endif

#-------------------------------------------------------------------------------
# Paths
#-------------------------------------------------------------------------------

# Root build directory (debug or release)
ifeq ($(findstring 1,$(DEBUG)),)
    DIR_BUILD       := Build/Release/
else
    DIR_BUILD       := Build/Debug/
endif

# Relative build directories
DIR_BUILD_PRODUCTS  := $(DIR_BUILD)Products/
DIR_BUILD_TEMP      := $(DIR_BUILD)Intermediates/
DIR_BUILD_TESTS     := $(DIR)Build/Tests/

#-------------------------------------------------------------------------------
# File suffixes
#-------------------------------------------------------------------------------

EXT_C   := .cpp
EXT_H   := .h
EXT_O   := .o

# Erases implicit rules
.SUFFIXES:

#-------------------------------------------------------------------------------
# Display
#-------------------------------------------------------------------------------

# Terminal colors
COLOR_NONE      := "\x1b[0m"
COLOR_GRAY      := "\x1b[30;01m"
COLOR_RED       := "\x1b[31;01m"
COLOR_GREEN     := "\x1b[32;01m"
COLOR_YELLOW    := "\x1b[33;01m"
COLOR_BLUE      := "\x1b[34;01m"
COLOR_PURPLE    := "\x1b[35;01m"
COLOR_CYAN      := "\x1b[36;01m"

#-------------------------------------------------------------------------------
# Functions
#-------------------------------------------------------------------------------

# Gets every C file in a specific source directory
# 
# @1:   The directory with the source files
GET_C_FILES = $(foreach _DIR,$(1), $(wildcard $(_DIR)*$(EXT_C)))

# Gets an SDK value from Xcode
# 
# @1:   The key for which to get the SDK value
XCODE_SDK_VALUE = "$(shell /usr/libexec/PlistBuddy -c "Print $(1)" /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist)"

# Prints a message about a file
# 
# @1:   The first message part
# @2:   The architecture
# @3:   The file
PRINT_FILE = $(call PRINT,$(1),$(2),$(subst /,.,$(subst ./,,$(dir $(3))))"$(COLOR_GRAY)"$(notdir $(3))"$(COLOR_NONE)")

# Prints a message
# 
# @1:   The first message part# @2:   The architecture
# @3:   The second message part
ifeq ($(findstring 1,$(DEBUG)),)
PRINT = "["$(COLOR_GREEN)" $(PRODUCT) "$(COLOR_NONE)"]> $(1) [ "$(COLOR_CYAN)"Release - $(2)"$(COLOR_NONE)" ]: "$(COLOR_YELLOW)"$(3)"$(COLOR_NONE)
else
PRINT = "["$(COLOR_GREEN)" $(PRODUCT) "$(COLOR_NONE)"]> $(1) [ "$(COLOR_CYAN)"Debug - $(2)"$(COLOR_NONE)" ]: "$(COLOR_YELLOW)"$(3)"$(COLOR_NONE)
endif

#-------------------------------------------------------------------------------
# Includes
#-------------------------------------------------------------------------------

__DIR__ := $(dir $(lastword $(MAKEFILE_LIST)))

ifeq ($(BUILD_TYPE),os-x)
    include $(__DIR__)/Platform/OSX.mk
else
    include $(__DIR__)/Platform/Linux.mk
endif
