#-------------------------------------------------------------------------------
# Copyright (c) 2015, Jean-David Gadina - www.xs-labs.com
# Distributed under the Boost Software License, Version 1.0.
# 
# Boost Software License - Version 1.0 - August 17th, 2003
# 
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
# 
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# File suffixes
#-------------------------------------------------------------------------------

# File extensions
EXT_LIB         := .a
EXT_DYLIB       := .dylib
EXT_FRAMEWORK   := .framework

#-------------------------------------------------------------------------------
# Products and architectures to build
#-------------------------------------------------------------------------------

PRODUCTS = $(PRODUCT_LIB)$(EXT_LIB)|i386|x86_64             \
           $(PRODUCT_DYLIB)$(EXT_DYLIB)|i386|x86_64         \
           $(PRODUCT_FRAMEWORK)$(EXT_FRAMEWORK)|i386|x86_64 \
           $(PRODUCT_IOS_LIB)$(EXT_LIB)|armv7|armv7s|arm64

#-------------------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------------------

LD := ld
AR := ar

#-------------------------------------------------------------------------------
# Commands configuration
#-------------------------------------------------------------------------------

# Architecture specific flags for ld
LD_FLAGS_i386               := 
LD_FLAGS_x86_64             := 
LD_FLAGS_armv7              := 
LD_FLAGS_armv7s             := 
LD_FLAGS_arm64              := 

# Architecture specific flags for ar
AR_FLAGS_i386               := rcs
AR_FLAGS_x86_64             := rcs
AR_FLAGS_armv7              := rcs
AR_FLAGS_armv7s             := rcs
AR_FLAGS_arm64              := rcs

# Architecture specific flags for the C compiler
CC_FLAGS_i386               := -arch i386
CC_FLAGS_x86_64             := -arch x86_64
CC_FLAGS_armv7              := -arch armv7 -isysroot $(IOS_SDK_PATH)
CC_FLAGS_armv7s             := -arch armv7s -isysroot $(IOS_SDK_PATH)
CC_FLAGS_arm64              := -arch arm64 -isysroot $(IOS_SDK_PATH)

# Architecture specific flags for the C compiler when creating a dynamic library
CC_FLAGS_DYLIB_i386         := -dynamiclib -install_name $(PREFIX_DYLIB)$(PRODUCT_DYLIB)$(EXT_DYLIB)
CC_FLAGS_DYLIB_x86_64       := -dynamiclib -install_name $(PREFIX_DYLIB)$(PRODUCT_DYLIB)$(EXT_DYLIB)

# Architecture specific flags for the C compiler when creating a Mac OS X framework
CC_FLAGS_FRAMEWORK_i386     := -dynamiclib -install_name $(PREFIX_FRAMEWORK)$(PRODUCT_FRAMEWORK)$(EXT_FRAMEWORK) -single_module -compatibility_version 1 -current_version 1
CC_FLAGS_FRAMEWORK_x86_64   := -dynamiclib -install_name $(PREFIX_FRAMEWORK)$(PRODUCT_FRAMEWORK)$(EXT_FRAMEWORK) -single_module -compatibility_version 1 -current_version 1
